# Generated by Django 3.0.1 on 2020-12-20 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('judge_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='Doctor_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Head_Jailer',
            fields=[
                ('head_jailer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('R', 'Retired'), ('S', 'In Service'), ('L', 'On Leave'), ('?', 'Unknown')], default='?', max_length=1)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='Head_Jailer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Jail',
            fields=[
                ('jail_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('prisoners_count', models.IntegerField(default=0)),
                ('doctors_count', models.IntegerField(default=0)),
                ('systems_count', models.IntegerField(default=0)),
                ('cells_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jailer',
            fields=[
                ('jailer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('R', 'Retired'), ('S', 'In Service'), ('L', 'On Leave'), ('?', 'Unknown')], default='?', max_length=1)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='Jailer_images/')),
                ('jail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Jail')),
            ],
        ),
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('prisoner_id', models.AutoField(primary_key=True, serialize=False)),
                ('prisoner_number', models.IntegerField()),
                ('picture', models.ImageField(upload_to='prisoners_images/')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('status', models.CharField(choices=[('J', 'In Jail'), ('D', 'Dead'), ('R', 'Realeased'), ('L', 'On Lose'), ('?', 'Unknown')], default='?', max_length=1)),
                ('crime_detail', models.CharField(max_length=2000)),
                ('case_no', models.CharField(max_length=200)),
                ('act', models.CharField(max_length=200)),
                ('punishment_type', models.CharField(max_length=200)),
                ('luggage', models.CharField(max_length=200)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('mental_health', models.CharField(max_length=200)),
                ('behaviour', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('privious_records', models.CharField(max_length=20000)),
                ('jail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Jail')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=2000)),
                ('picture', models.ImageField(upload_to='Visitor_images/')),
            ],
        ),
        migrations.CreateModel(
            name='prisoner_meetings',
            fields=[
                ('prisoner_meetings_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('details', models.CharField(max_length=200)),
                ('luggage', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('D', 'Complete'), ('P', 'Pending'), ('C', 'Canceled'), ('?', 'Unknown')], default='?', max_length=1)),
                ('jail_incharge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Jailer')),
                ('prisoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Prisoner')),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='prisoner_medications',
            fields=[
                ('prisoner_medications_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('doctor_advise', models.CharField(max_length=200)),
                ('health_issue', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Doctor')),
                ('jail_incharge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Jailer')),
                ('prisoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Prisoner')),
            ],
        ),
        migrations.CreateModel(
            name='prisoner_jail_shiftiting',
            fields=[
                ('prisoner_jail_shiftiting_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=200)),
                ('carrier', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('D', 'Complete'), ('P', 'Pending'), ('C', 'Canceled'), ('?', 'Unknown')], default='?', max_length=1)),
                ('court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Court')),
                ('jail_incharge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Jailer')),
                ('new_jail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_jail_id', to='AdminPanel.Jail')),
                ('previous_jail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_jail_id', to='AdminPanel.Jail')),
                ('prisoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Prisoner')),
            ],
        ),
        migrations.CreateModel(
            name='prisoner_herarings',
            fields=[
                ('prisoner_hearing_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_out', models.DateTimeField()),
                ('time_in', models.DateTimeField()),
                ('status', models.CharField(choices=[('C', 'Canceled'), ('D', 'Done'), ('L', 'Late'), ('?', 'Unknown')], default='?', max_length=1)),
                ('court_orders', models.CharField(max_length=2000)),
                ('details', models.CharField(max_length=2000)),
                ('court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Court')),
                ('head_jailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Head_Jailer')),
                ('jailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Jailer')),
                ('prisoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Prisoner')),
            ],
        ),
        migrations.AddField(
            model_name='head_jailer',
            name='jail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Jail'),
        ),
    ]
