# Generated by Django 3.0.1 on 2020-12-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_auto_20201220_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
